"""update model employee

Revision ID: 6e76dd764118
Revises: c5c086b9aa6e
Create Date: 2024-07-10 11:38:23.948958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e76dd764118'
down_revision: Union[str, None] = 'c5c086b9aa6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_role', table_name='employee')
    op.drop_column('employee', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.create_index('ix_employee_role', 'employee', ['role'], unique=False)
    # ### end Alembic commands ###
